In [1]:
import pandas as pd
df = pd.read_csv('pokemon.csv')
# df = pd.read_csv('pokemon.csv', delimiter='\t')
# df = pd.read_excel('pokemon.xlsx')
df.head()

c:\softwares\python3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\softwares\python3\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
c:\softwares\python3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [16]:
df.columns.values
df[['Name', '#', 'Type 1']][0:5]
df.iloc[1]  # Integer Location for row access
df.iloc[2, 5]  # [Row, Column] ---> always numbers

# for index, row in df.iterrows():
#     print(row.Name)

df.loc[df["Type 1"] == 'Grass']  # Locate not just integers, but all sorts of data

df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [19]:
df.sort_values('Name')
df.sort_values(['Type 1', 'Attack'], ascending=[True, False])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False
650,589,Escavalier,Bug,Steel,70,135,105,60,105,20,5,False
228,212,Scizor,Bug,Steel,70,130,100,55,80,65,2,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
717,649,Genesect,Bug,Steel,71,120,95,120,95,99,5,False
132,123,Scyther,Bug,Flying,70,110,80,55,80,105,1,False
693,632,Durant,Bug,Steel,58,109,112,48,48,109,5,False
602,542,Leavanny,Bug,Grass,75,103,80,70,80,92,5,False
605,545,Scolipede,Bug,Poison,60,100,89,55,69,112,5,False
52,47,Parasect,Bug,Grass,60,95,80,60,80,30,1,False
619,558,Crustle,Bug,Rock,70,95,125,65,75,45,5,False
461,414,Mothim,Bug,Flying,70,94,50,94,50,66,4,False
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
182,168,Ariados,Bug,Poison,70,90,70,60,60,40,2,False
220,205,Forretress,Bug,Steel,75,90,140,60,60,40,2,False
315,291,Ninjask,Bug,Flying,61,90,45,50,50,160,3,False
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False
447,402,Kricketune,Bug,NaN,77,85,51,55,51,65,4,False
697,636,Larvesta,Bug,Fire,55,85,55,50,55,60,5,False
463,416,Vespiquen,Bug,Flying,70,80,102,80,102,40,4,False
459,413,WormadamSandy Cloak,Bug,Ground,60,79,105,59,85,36,4,False
657,596,Galvantula,Bug,Electric,70,77,60,97,60,108,5,False
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
649,588,Karrablast,Bug,NaN,50,75,45,40,45,60,5,False
342,313,Volbeat,Bug,NaN,65,73,55,47,75,85,3,False
51,46,Paras,Bug,Grass,35,70,55,45,55,25,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
560,501,Oshawott,Water,NaN,55,55,45,63,45,45,5,False
574,515,Panpour,Water,NaN,50,53,48,53,48,64,5,False
762,692,Clauncher,Water,NaN,50,53,62,58,63,44,6,False
59,54,Psyduck,Water,NaN,50,52,48,65,50,55,1,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False
65,60,Poliwag,Water,NaN,40,50,40,40,40,90,1,False
199,184,Azumarill,Water,Fairy,100,50,80,60,80,50,2,False
294,271,Lombre,Water,Grass,60,50,50,60,70,50,3,False
302,279,Pelipper,Water,Flying,60,50,100,85,70,65,3,False
595,535,Tympole,Water,NaN,50,50,40,50,40,64,5,False
506,456,Finneon,Water,NaN,49,49,56,49,61,66,4,False
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False
371,339,Barboach,Water,Ground,50,48,43,46,41,60,3,False
469,422,Shellos,Water,NaN,76,48,48,57,62,34,4,False
93,86,Seel,Water,NaN,65,45,55,45,70,45,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
209,194,Wooper,Water,Ground,55,45,45,25,25,15,2,False
641,580,Ducklett,Water,Flying,62,44,50,44,50,55,5,False
78,72,Tentacool,Water,Poison,40,40,35,50,100,70,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
244,226,Mantine,Water,Flying,65,40,70,80,140,70,2,False
653,592,Frillish,Water,Ghost,55,40,50,65,85,40,5,False
184,170,Chinchou,Water,Electric,75,38,38,56,56,67,2,False
293,270,Lotad,Water,Grass,40,30,30,40,50,30,3,False
301,278,Wingull,Water,Flying,40,30,30,55,30,85,3,False
405,370,Luvdisc,Water,NaN,43,30,55,40,65,97,3,False
198,183,Marill,Water,Fairy,70,20,50,20,50,40,2,False
508,458,Mantyke,Water,Flying,45,20,50,60,120,50,4,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False

In [55]:
# Add Column -----> Total is the new column  FIRST METHOD
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
df.head(5)
# df.sort_values("Total", ascending=False)
df = df.drop(columns=['Total'])  # Or 'Total', axis=1 for columns

## SECOND METHOD
df["Total"] = df.iloc[:, 4:10].sum(axis=1)
df.head()

cols = list(df.columns)
print(type(df.columns.values))

print(cols[0:4] + [cols[-1]] + cols[4:12])
df = df[cols[0:4] + [cols[-1]] + cols[4:12]]
df.head()

<class 'numpy.ndarray'>
['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [58]:
# Save new df
df.to_csv("new_pokemon.csv", index=False)
df.to_csv("new_pokemon_tabs.txt", index=False, delimiter='\t')
df.to_excel("newpokemon.xlsx")

TypeError: to_csv() got an unexpected keyword argument 'delimiter'